# all test tables can be built without errors or warnings

    Problem with `mutate()` column `col_i`.
    i `col_i = fct_expand(...)`.
    x object 'col_i' not found
    Caused by error:
    ! object 'col_i' not found

